---
deployment:
  tasks:
    - /bin/mkdir -p /home/devcente/backend
    - /bin/mkdir -p /home/devcente/public_html
    - /bin/mkdir -p /home/devcente/scripts
    - /bin/cp -Rf backend/. /home/devcente/backend/
    - /bin/cp -Rf public_html/. /home/devcente/public_html/
    - /bin/cp -rf scripts/* /home/devcente/scripts/
    - /bin/chmod +x /home/devcente/scripts/*.sh
    - /bin/bash /home/devcente/scripts/deploy-cpanel.sh
