<?php

declare(strict_types=1);

return [
    'title' => 'Business Reports & Analytics',
    'export_generated' => 'Report exported successfully.',
    'unauthorized' => 'You do not have permission to view or export this report.',
    'freshness' => [
        'live' => 'Live Real-time Data',
        'near_real_time' => 'Near Real-time (15 min cache)',
        'batch_daily' => 'Daily Snapshot',
    ],
    'export' => [
        'csv' => 'Comma Separated Values (CSV)',
        'xlsx' => 'Excel Spreadsheet (XLSX)',
        'pdf' => 'Portable Document Format (PDF)',
        'generated_at' => 'Generated on :date',
        'generated_by' => 'Generated by :name',
        'confidential' => 'Confidential - Internal Business Operations',
    ],
];
