import type { ReportDefinition, ReportDataResponse, ReportColumnDefinition } from '../../types/api/reports';

export interface ModuleCategory {
  id: string;
  name: string;
  shortName: string;
  iconName: string;
  description: string;
  badgeTone: string;
}

export const REPORT_MODULES: ModuleCategory[] = [
  {
    id: 'all',
    name: 'All Modules',
    shortName: 'All',
    iconName: 'Layers',
    description: 'Comprehensive enterprise reporting across all operations.',
    badgeTone: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  {
    id: 'production',
    name: 'Production & Manufacturing',
    shortName: 'Production',
    iconName: 'Factory',
    description: 'Output yield, batch run-rates, scrap ratios, and worker piece rates.',
    badgeTone: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    id: 'inventory',
    name: 'Inventory & Warehouse',
    shortName: 'Inventory',
    iconName: 'Boxes',
    description: 'Stock valuation, ledger movements, safety stock alerts, and transfers.',
    badgeTone: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  {
    id: 'purchasing',
    name: 'Purchase & Procurement',
    shortName: 'Purchasing',
    iconName: 'ShoppingBag',
    description: 'PO status, supplier lead times, GRN inspection, and accounts payable.',
    badgeTone: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    id: 'sales',
    name: 'Sales & POS Counters',
    shortName: 'Sales & POS',
    iconName: 'Receipt',
    description: 'Omnichannel revenue, counter shifts, split tenders, and sales returns.',
    badgeTone: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
  {
    id: 'profit',
    name: 'Profitability & Margins',
    shortName: 'Profitability',
    iconName: 'TrendingUp',
    description: 'Gross margin by SKU, invoice profitability, and net contribution.',
    badgeTone: 'bg-violet-50 text-violet-700 border-violet-200',
  },
  {
    id: 'crm',
    name: 'CRM & Commercial Leads',
    shortName: 'CRM',
    iconName: 'Users',
    description: 'Pipeline funnel, fake lead verification audits, and conversion rates.',
    badgeTone: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    id: 'salesmen',
    name: 'Salesman Targets & Quotas',
    shortName: 'Salesmen',
    iconName: 'Target',
    description: 'Monthly quota tracking, achievement %, profit generated, and tiered incentives.',
    badgeTone: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  {
    id: 'delivery',
    name: 'Delivery & Logistics',
    shortName: 'Delivery',
    iconName: 'Truck',
    description: 'Courier fulfillment (Pathao/Steadfast), RTO returns, and COD settlement.',
    badgeTone: 'bg-sky-50 text-sky-700 border-sky-200',
  },
  {
    id: 'hr',
    name: 'HR & Workforce Payroll',
    shortName: 'HR & Payroll',
    iconName: 'UserCheck',
    description: 'Attendance, piece-rate wages, overtime units, and disbursed net payroll.',
    badgeTone: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  {
    id: 'finance',
    name: 'Finance & Accounts Ledger',
    shortName: 'Finance',
    iconName: 'DollarSign',
    description: 'Trial balance, profit & loss, operating expenses, and AR/AP aging.',
    badgeTone: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  },
  {
    id: 'assets',
    name: 'Fixed Asset Management',
    shortName: 'Assets',
    iconName: 'Cpu',
    description: 'Asset register, net book value (NBV), maintenance logs, and depreciation.',
    badgeTone: 'bg-slate-100 text-slate-700 border-slate-300',
  },
  {
    id: 'qc',
    name: 'QC & Audit Compliance',
    shortName: 'QC & Audit',
    iconName: 'ShieldCheck',
    description: 'AQL 2.5 inspection pass/fail rates, defect tags, and regulatory audit logs.',
    badgeTone: 'bg-purple-50 text-purple-700 border-purple-200',
  },
];

export const ALL_REPORT_DEFINITIONS: ReportDefinition[] = [
  // PRODUCTION
  {
    id: 1,
    uuid: 'rpt-prod-01',
    code: 'daily_production',
    name: 'Daily Production Report',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily output units planned vs actual produced per line and shift.',
  },
  {
    id: 2,
    uuid: 'rpt-prod-02',
    code: 'monthly_production',
    name: 'Monthly Production Summary',
    module: 'production',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Aggregated monthly production volume, capacity utilization %, and schedule adherence.',
  },
  {
    id: 3,
    uuid: 'rpt-prod-03',
    code: 'production_target_vs_achievement',
    name: 'Production Target vs Achievement',
    module: 'production',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Comparative variance between factory target goals and actual manufactured output.',
  },
  {
    id: 4,
    uuid: 'rpt-prod-04',
    code: 'production_yield',
    name: 'Production Yield & Scrap Analysis',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Batch-level yield efficiency %, actual vs planned output, and defect rejection count.',
  },
  {
    id: 5,
    uuid: 'rpt-prod-05',
    code: 'worker_production',
    name: 'Worker Piece-Rate Production Log',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Line operator individual output logs, hours worked, and earned piece-rate values.',
  },
  {
    id: 6,
    uuid: 'rpt-prod-06',
    code: 'line_wise_production',
    name: 'Line-wise Production & Bottlenecks',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Assembly line efficiency, hourly run rates (pcs/hr), downtime, and bottlenecks.',
  },
  {
    id: 7,
    uuid: 'rpt-prod-07',
    code: 'production_wastage_scrap',
    name: 'Production Wastage, Rework & Scrap',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Material wastage logs, rework labor hours, and scrap value write-offs.',
  },

  // INVENTORY
  {
    id: 10,
    uuid: 'rpt-inv-01',
    code: 'stock_valuation',
    name: 'Warehouse Stock Valuation & Aging',
    module: 'inventory',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'On-hand inventory valued at weighted average cost with FIFO aging brackets.',
  },
  {
    id: 11,
    uuid: 'rpt-inv-02',
    code: 'current_stock',
    name: 'Current Stock On-Hand & Levels',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Live physical stock, reserved quantities, and available units per warehouse.',
  },
  {
    id: 12,
    uuid: 'rpt-inv-03',
    code: 'stock_ledger',
    name: 'Perpetual Stock Ledger',
    module: 'inventory',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Chronological audit trail of all inventory receipts, issues, and adjustments.',
  },
  {
    id: 13,
    uuid: 'rpt-inv-04',
    code: 'low_stock',
    name: 'Low Stock & Reorder Thresholds',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Items approaching safety stock levels requiring immediate replenishment.',
  },
  {
    id: 14,
    uuid: 'rpt-inv-05',
    code: 'warehouse_transfer',
    name: 'Warehouse Inter-Transfer Log',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Completed, in-transit, and pending stock transfer notes between facilities.',
  },
  {
    id: 15,
    uuid: 'rpt-inv-06',
    code: 'damaged_stock',
    name: 'Damaged & Written-off Stock',
    module: 'inventory',
    category: 'operational',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Damaged items logged from transit, factory floor, or warehouse accidents.',
  },

  // PURCHASING
  {
    id: 20,
    uuid: 'rpt-pur-01',
    code: 'purchase_summary',
    name: 'Purchase Order (PO) Summary',
    module: 'purchasing',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Overview of open, partially received, closed, and cancelled purchase orders.',
  },
  {
    id: 21,
    uuid: 'rpt-pur-02',
    code: 'purchase_details',
    name: 'Purchase Details & GRN Log',
    module: 'purchasing',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Goods Receipt Notes (GRN) with received quantities and inspection status.',
  },
  {
    id: 22,
    uuid: 'rpt-pur-03',
    code: 'supplier_due',
    name: 'Supplier Payables & Aging Ledger',
    module: 'purchasing',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Outstanding supplier balances categorized by 0-30, 31-60, 61-90, 90+ days aging.',
  },

  // SALES & POS
  {
    id: 30,
    uuid: 'rpt-sls-01',
    code: 'sales_performance',
    name: 'Channel Sales & Revenue Ledger',
    module: 'sales',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Order volume, gross sales revenue, applied discounts, and payment settlement.',
  },
  {
    id: 31,
    uuid: 'rpt-sls-02',
    code: 'daily_sales',
    name: 'Daily Sales & Revenue Ledger',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily order volume, gross receipts, applied discounts, and net collected revenue.',
  },
  {
    id: 32,
    uuid: 'rpt-sls-03',
    code: 'pos_counter_sales',
    name: 'POS Counter Shift & Tender Reconciliation',
    module: 'sales',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Shift opening cash, cash sales, card payments, mobile banking, and variance.',
  },
  {
    id: 33,
    uuid: 'rpt-sls-04',
    code: 'b2b_sales',
    name: 'B2B Wholesale Sales Ledger',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Bulk wholesale order volume, invoice balances, and institutional payment terms.',
  },
  {
    id: 34,
    uuid: 'rpt-sls-05',
    code: 'sales_return',
    name: 'Sales Returns & Credit Notes',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Customer return items, return reasons, refund types, and restocked units.',
  },

  // PROFITABILITY
  {
    id: 40,
    uuid: 'rpt-prf-01',
    code: 'invoice_profit',
    name: 'Invoice-wise Gross Profit Analysis',
    module: 'profit',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Individual commercial invoices analyzed by sales price minus COGS.',
  },
  {
    id: 41,
    uuid: 'rpt-prf-02',
    code: 'product_profit',
    name: 'Product-wise Profit & Gross Margin %',
    module: 'profit',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Gross margin ranking and contribution percentage calculated across catalog.',
  },

  // CRM & LEADS
  {
    id: 50,
    uuid: 'rpt-crm-01',
    code: 'lead_summary',
    name: 'Commercial Lead Pipeline Summary',
    module: 'crm',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Total leads across pipeline stages: New, Contacted, Qualified, Converted, Lost.',
  },
  {
    id: 51,
    uuid: 'rpt-crm-02',
    code: 'fake_leads_audit',
    name: 'Fake & Invalid Lead Verification Audit',
    module: 'crm',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Audit log of unverified, unreachable, or flagged fraudulent customer inquiries.',
  },
  {
    id: 52,
    uuid: 'rpt-crm-03',
    code: 'conversion_rate_source',
    name: 'Lead Conversion Rate by Source',
    module: 'crm',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Conversion efficiency calculated across Facebook, Storefront, WhatsApp, and Walk-ins.',
  },

  // SALESMEN
  {
    id: 60,
    uuid: 'rpt-rep-01',
    code: 'salesman_quota_achievement',
    name: 'Salesman Monthly Quota vs Achievement',
    module: 'salesmen',
    category: 'executive',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Assigned monthly targets (৳) vs achieved revenue and completion percentage.',
  },
  {
    id: 61,
    uuid: 'rpt-rep-02',
    code: 'salesman_remaining_target',
    name: 'Salesman Remaining Target & Shortfall',
    module: 'salesmen',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Pending sales shortfall required for each salesman to meet monthly quotas.',
  },
  {
    id: 62,
    uuid: 'rpt-rep-03',
    code: 'salesman_incentive_accrual',
    name: 'Salesman Tiered Incentive Accrual',
    module: 'salesmen',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Tiered commission calculations, approved bonuses, and pending disbursements.',
  },
  {
    id: 63,
    uuid: 'rpt-rep-04',
    code: 'salesman_leaderboard',
    name: 'Sales Representative Leaderboard',
    module: 'salesmen',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Ranked performance metrics across sales reps by conversion rate, profit, and volume.',
  },

  // DELIVERY
  {
    id: 70,
    uuid: 'rpt-del-01',
    code: 'pending_deliveries',
    name: 'Pending Deliveries & Dispatch Queue',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Parcels packaged and staged for courier pickup or vehicle loading.',
  },
  {
    id: 71,
    uuid: 'rpt-del-02',
    code: 'delivered_orders',
    name: 'Delivered Shipments & POD Log',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Successfully completed shipments with Proof of Delivery (POD) confirmations.',
  },
  {
    id: 72,
    uuid: 'rpt-del-03',
    code: 'courier_performance',
    name: 'Courier Performance (Pathao/Steadfast)',
    module: 'delivery',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Courier success rate %, average delivery transit time, and SLA performance.',
  },
  {
    id: 73,
    uuid: 'rpt-del-04',
    code: 'cod_reconciliation',
    name: 'Cash On Delivery (COD) Reconciliation',
    module: 'delivery',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Courier collected cash reconciliation vs actual bank deposits received.',
  },

  // HR & PAYROLL
  {
    id: 80,
    uuid: 'rpt-hr-01',
    code: 'payroll_summary',
    name: 'Disbursed Payroll Register & Net Pay',
    module: 'hr',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Aggregated gross earnings, piece-rate bonuses, deductions, and net payouts.',
  },
  {
    id: 81,
    uuid: 'rpt-hr-02',
    code: 'daily_attendance',
    name: 'Daily & Monthly Attendance Log',
    module: 'hr',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily check-in, late arrival records, early departures, and approved leaves.',
  },
  {
    id: 82,
    uuid: 'rpt-hr-03',
    code: 'sales_commission_payout',
    name: 'Sales Commission & Incentive Payouts',
    module: 'hr',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Approved commercial sales incentives transferred to payroll disbursement.',
  },

  // FINANCE & ACCOUNTS
  {
    id: 90,
    uuid: 'rpt-fin-01',
    code: 'gl_summary',
    name: 'General Ledger Summary Trial Balance',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Debit and credit balance reconciliation across all active GL accounts.',
  },
  {
    id: 91,
    uuid: 'rpt-fin-02',
    code: 'customer_ar_aging',
    name: 'Customer Receivables (AR) Aging (0-90+ Days)',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Outstanding B2B trade receivables categorized by 0-30, 31-60, 61-90, 90+ days.',
  },
  {
    id: 92,
    uuid: 'rpt-fin-03',
    code: 'operating_expenses',
    name: 'Operating Expense Breakdown by Category',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Factory overhead, power/utilities, logistics fees, rent, and administration.',
  },
  {
    id: 93,
    uuid: 'rpt-fin-04',
    code: 'cash_bank_ledger',
    name: 'Cash & Bank Accounts Ledger',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Balances across all company bank accounts, petty cash, and payment gateways.',
  },

  // ASSETS
  {
    id: 100,
    uuid: 'rpt-ast-01',
    code: 'fixed_asset_register',
    name: 'Fixed Asset Register & Inventory',
    module: 'assets',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Comprehensive register of factory machinery, cutting tables, vehicles, and IT.',
  },
  {
    id: 101,
    uuid: 'rpt-ast-02',
    code: 'asset_valuation_nbv',
    name: 'Asset Valuation & Net Book Value (NBV)',
    module: 'assets',
    category: 'financial',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Asset acquisition cost, cumulative depreciation, and current book valuation.',
  },
  {
    id: 102,
    uuid: 'rpt-ast-03',
    code: 'asset_maintenance_log',
    name: 'Asset Maintenance, Repairs & Downtime',
    module: 'assets',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Preventive maintenance history, emergency breakdown repairs, and parts replacement.',
  },

  // QC & AUDIT
  {
    id: 110,
    uuid: 'rpt-qc-01',
    code: 'qc_inspection_ratio',
    name: 'QC Inspection Pass / Fail Ratios',
    module: 'qc',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Quality pass rates and defect percentage evaluated against AQL 2.5 standards.',
  },
  {
    id: 111,
    uuid: 'rpt-qc-02',
    code: 'defect_categorization',
    name: 'Defect Categorization (Critical/Major/Minor)',
    module: 'qc',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Categorization of stitching flaws, oil stains, measurement faults, and runs.',
  },
  {
    id: 112,
    uuid: 'rpt-qc-03',
    code: 'compliance_audit_trail',
    name: 'System Compliance & Transaction Audit Trail',
    module: 'qc',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Security and financial audit trail of critical operational actions.',
  },
  // ADDITIONAL CANONICAL ENTERPRISE REPORTS (SYNCHRONIZED TO 84 TOTAL)
  {
    id: 100,
    uuid: 'rpt-auto-total_input_output',
    code: 'total_input_output',
    name: 'Total Input vs Output Analysis',
    module: 'production',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Mass balance ratio of raw material inputs against completed finished goods output.',
  },
  {
    id: 101,
    uuid: 'rpt-auto-product_wise_production',
    code: 'product_wise_production',
    name: 'Product-wise Production Analysis',
    module: 'production',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Manufactured quantities, cycle times, and output volume segmented by product SKU.',
  },
  {
    id: 102,
    uuid: 'rpt-auto-factory_wise_production',
    code: 'factory_wise_production',
    name: 'Factory-wise Production Matrix',
    module: 'production',
    category: 'executive',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Multi-factory comparison of overall manufacturing output, capacity, and active lines.',
  },
  {
    id: 103,
    uuid: 'rpt-auto-shift_wise_production',
    code: 'shift_wise_production',
    name: 'Shift-wise Production & Efficiency',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Output variance, labor utilization, and efficiency comparing Day vs Night shifts.',
  },
  {
    id: 104,
    uuid: 'rpt-auto-production_efficiency',
    code: 'production_efficiency',
    name: 'Production Efficiency & Cycle Variance',
    module: 'production',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Overall Equipment Effectiveness (OEE) and standard minute value (SMV) variances.',
  },
  {
    id: 105,
    uuid: 'rpt-auto-stock_movement',
    code: 'stock_movement',
    name: 'Stock Movement & Velocity (In/Out)',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Fast vs slow-moving stock velocity, turnover rates, and movement history.',
  },
  {
    id: 106,
    uuid: 'rpt-auto-out_of_stock',
    code: 'out_of_stock',
    name: 'Out of Stock & Stockout Impact',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Items with zero available inventory and associated open sales demand.',
  },
  {
    id: 107,
    uuid: 'rpt-auto-warehouse_stock',
    code: 'warehouse_stock',
    name: 'Warehouse Stock Distribution',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Cross-facility stock distribution across Central Factory, Retail Outlets, and In-Transit.',
  },
  {
    id: 108,
    uuid: 'rpt-auto-raw_material_stock',
    code: 'raw_material_stock',
    name: 'Raw Material Stock Valuation',
    module: 'inventory',
    category: 'financial',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Valuation of fabrics, trims, chemicals, and packaging materials on hand.',
  },
  {
    id: 109,
    uuid: 'rpt-auto-finished_goods_stock',
    code: 'finished_goods_stock',
    name: 'Finished Goods Inventory Status',
    module: 'inventory',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Commercial valuation of finished apparel ready for wholesale and retail dispatch.',
  },
  {
    id: 110,
    uuid: 'rpt-auto-supplier_purchase',
    code: 'supplier_purchase',
    name: 'Supplier-wise Purchase Analysis',
    module: 'purchasing',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Procurement volume, financial spend, and vendor fulfillment lead time compliance.',
  },
  {
    id: 111,
    uuid: 'rpt-auto-product_purchase',
    code: 'product_purchase',
    name: 'Raw Material Purchase Price Trends',
    module: 'purchasing',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Historical cost fluctuations per kilogram/meter across supplier quotes over time.',
  },
  {
    id: 112,
    uuid: 'rpt-auto-purchase_return',
    code: 'purchase_return',
    name: 'Purchase Returns & Debit Notes',
    module: 'purchasing',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Returned defective vendor materials and associated debit adjustments.',
  },
  {
    id: 113,
    uuid: 'rpt-auto-supplier_payment_history',
    code: 'supplier_payment_history',
    name: 'Supplier Payment Disbursement History',
    module: 'purchasing',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Chronological record of vendor payments made via bank transfer, check, and cash.',
  },
  {
    id: 114,
    uuid: 'rpt-auto-monthly_sales',
    code: 'monthly_sales',
    name: 'Monthly Sales Velocity & Trends',
    module: 'sales',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Month-over-month sales trends, seasonal velocity, and average order value (AOV).',
  },
  {
    id: 115,
    uuid: 'rpt-auto-product_sales',
    code: 'product_sales',
    name: 'Product-wise Sales Analysis',
    module: 'sales',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Best-selling SKUs, inventory turnover speed, and revenue per product style.',
  },
  {
    id: 116,
    uuid: 'rpt-auto-customer_sales',
    code: 'customer_sales',
    name: 'Customer & Client-wise Sales Volume',
    module: 'sales',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'B2B institutional client purchasing volume, credit terms, and order frequency.',
  },
  {
    id: 117,
    uuid: 'rpt-auto-salesman_sales',
    code: 'salesman_sales',
    name: 'Salesman Sales Attribution',
    module: 'sales',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Revenue directly attributed to assigned showroom and field sales representatives.',
  },
  {
    id: 118,
    uuid: 'rpt-auto-b2c_sales',
    code: 'b2c_sales',
    name: 'B2C & Online Storefront Sales',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Online customer orders, storefront conversion rates, and digital payments.',
  },
  {
    id: 119,
    uuid: 'rpt-auto-salesman_profitability',
    code: 'salesman_profitability',
    name: 'Salesman Profitability Contribution',
    module: 'profit',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Net profit generated per salesperson after subtracting product cost and commissions.',
  },
  {
    id: 120,
    uuid: 'rpt-auto-daily_profit',
    code: 'daily_profit',
    name: 'Daily Gross Profit Ledger',
    module: 'profit',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily gross profit totals comparing billed revenue with estimated goods cost.',
  },
  {
    id: 121,
    uuid: 'rpt-auto-monthly_profit',
    code: 'monthly_profit',
    name: 'Monthly Profit & Loss Summary',
    module: 'profit',
    category: 'executive',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Comprehensive monthly bottom-line summary comparing revenues, COGS, and factory expenses.',
  },
  {
    id: 122,
    uuid: 'rpt-auto-salesman_leads',
    code: 'salesman_leads',
    name: 'Salesman Lead Allocation & Workload',
    module: 'crm',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Active workload distribution and assigned leads per sales representative.',
  },
  {
    id: 123,
    uuid: 'rpt-auto-lead_status_distribution',
    code: 'lead_status_distribution',
    name: 'Lead Status & Stage Distribution',
    module: 'crm',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Distribution breakdown of active customer inquiries across lifecycle stages.',
  },
  {
    id: 124,
    uuid: 'rpt-auto-converted_leads',
    code: 'converted_leads',
    name: 'Converted Leads & Deal Value',
    module: 'crm',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Successful conversions resulting in confirmed invoices and sales revenue.',
  },
  {
    id: 125,
    uuid: 'rpt-auto-lost_leads_analysis',
    code: 'lost_leads_analysis',
    name: 'Lost Leads & Rejection Analysis',
    module: 'crm',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Analysis of reasons behind lost opportunities (pricing, stock availability, competitor).',
  },
  {
    id: 126,
    uuid: 'rpt-auto-salesman_profit_contribution',
    code: 'salesman_profit_contribution',
    name: 'Salesman Net Profit Contribution',
    module: 'salesmen',
    category: 'financial',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Actual gross margin and profit delivered by each sales agent beyond revenue.',
  },
  {
    id: 127,
    uuid: 'rpt-auto-returned_orders',
    code: 'returned_orders',
    name: 'Returned (RTO) Consignments',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Return-to-origin packages, failed delivery attempts, and customer rejection logs.',
  },
  {
    id: 128,
    uuid: 'rpt-auto-cancelled_deliveries',
    code: 'cancelled_deliveries',
    name: 'Cancelled Delivery Dispatches',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Orders cancelled after consignment creation and returned to warehouse shelves.',
  },
  {
    id: 129,
    uuid: 'rpt-auto-delivery_sla_history',
    code: 'delivery_sla_history',
    name: 'Delivery SLA & Transit Time History',
    module: 'delivery',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Historical delivery duration tracking across Dhaka Metro vs Divisional areas.',
  },
  {
    id: 130,
    uuid: 'rpt-auto-employee_directory',
    code: 'employee_directory',
    name: 'Employee Directory & Workforce Distribution',
    module: 'hr',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Headcount distribution across Factory Lines, Sales, Logistics, and Administration.',
  },
  {
    id: 131,
    uuid: 'rpt-auto-worker_piece_rate_summary',
    code: 'worker_piece_rate_summary',
    name: 'Worker Piece-Rate Production Log',
    module: 'hr',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Production worker piece-rate units completed, base pay, and piece bonus accrual.',
  },
  {
    id: 132,
    uuid: 'rpt-auto-income_statement',
    code: 'income_statement',
    name: 'Income & Profit/Loss Statement',
    module: 'finance',
    category: 'financial',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Operating revenues, cost of sales, operating expenditures, and net income.',
  },
  {
    id: 133,
    uuid: 'rpt-auto-supplier_ap_aging',
    code: 'supplier_ap_aging',
    name: 'Supplier Payables (AP) Aging',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Vendor bills due for settlement with payment terms and aging breakdown.',
  },
  {
    id: 134,
    uuid: 'rpt-auto-payment_method_summary',
    code: 'payment_method_summary',
    name: 'Payment Method Tender Summary',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Aggregated inflows categorized by Cash, POS Card, Bank EFT, bKash, and Nagad.',
  },
  {
    id: 135,
    uuid: 'rpt-auto-assigned_assets',
    code: 'assigned_assets',
    name: 'Assigned Assets by Employee & Line',
    module: 'assets',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Assets checked out to specific factory assembly lines, drivers, and supervisors.',
  },
  {
    id: 136,
    uuid: 'rpt-auto-asset_disposal_history',
    code: 'asset_disposal_history',
    name: 'Asset Disposal, Salvage & Write-off History',
    module: 'assets',
    category: 'compliance',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Retired equipment, salvage amounts recovered, and scrap write-offs.',
  },
];// Production-grade empty fallback structure — ZERO mock/fake records
export const REPORT_FALLBACK_DATA: Record<string, ReportDataResponse> = {};

/**
 * Returns a clean, production-grade empty report dataset for any report definition code,
 * deriving schema columns from the definition without fake records.
 */
export function getReportFallbackData(_code: string, def?: ReportDefinition): ReportDataResponse {
  const columns: Record<string, ReportColumnDefinition> = {};

  if (def?.available_columns && typeof def.available_columns === 'object') {
    for (const [colKey, colDef] of Object.entries(def.available_columns)) {
      if (typeof colDef === 'string') {
        columns[colKey] = {
          label: colDef.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
          type: 'string',
          sortable: true,
        };
      } else if (typeof colDef === 'object' && colDef !== null) {
        const c = colDef as { label?: string; type?: string; sortable?: boolean };
        const validTypes = ['string', 'number', 'currency', 'date', 'badge', 'percentage'] as const;
        const resolvedType = (validTypes as readonly string[]).includes(c.type ?? '')
          ? (c.type as (typeof validTypes)[number])
          : 'string';
        columns[colKey] = {
          label: c.label || colKey.replace(/_/g, ' ').replace(/\b\w/g, (x) => x.toUpperCase()),
          type: resolvedType,
          sortable: c.sortable ?? true,
        };
      }
    }
  }

  // Fallback minimal columns if none specified in definition
  if (Object.keys(columns).length === 0) {
    columns['id'] = { label: 'Reference / Code', type: 'string', sortable: true };
    columns['date'] = { label: 'Date', type: 'date', sortable: true };
    columns['title'] = { label: 'Description', type: 'string', sortable: true };
    columns['amount'] = { label: 'Amount', type: 'currency', sortable: true };
    columns['status'] = { label: 'Status', type: 'badge', sortable: true };
  }

  return {
    columns,
    data: [],
    summary: {},
    pagination: {
      total: 0,
      current_page: 1,
      per_page: 25,
      last_page: 1,
    },
    meta: {
      freshness: {
        as_of: new Date().toISOString(),
        tier: def?.tier || 'live',
        stale: false,
      },
    },
  };
}
